baseurl = "/"
host = "https://fr.maxgoldhouse.com"
title = "Villamartin Propri&eacute;t&eacute; a vendre, Playa Flamenca, Cabo Roig, Guardamar del Segura, Ciudad Quesada Costa Blanca Spain"
relativeURLs = true

[params]
  desite = "https://de.maxgoldhouse.com"
  ensite = "https://www.maxgoldhouse.com"
  nlsite = "https://nl.maxgoldhouse.com"
  netlifyhost = "https://mgh-fr.netlify.app"
  host = "https://mgh-3-fr.firebaseapp.com"
  phone = "+34 657 612 295"
  email = "ellen@maxgoldhouse.com"
  address = "03191 Pinar de Campoverde (Alicante)"
  company = "MaxGoldHouse"
  director = "Ellen Van den Broek"
  sold = "V E N D U"

[taxonomies]
  maison = "maisons"

[outputs]
    page = ["json","html"]
    section = ["json"] 
    maison = ["json","html"]
    contact = ["html"]
    politique = ["html"]